#Application
spring.application.name=kardex-eletronico
server.port=3307
spring.config.import=optional:file:./config/application-secrets.properties

api.security.token.secret=${JWT_TOKEN:my_secret_key}

#Jackson
spring.jackson.property-naming-strategy=SNAKE_CASE

#JPA
spring.jpa.hibernate.ddl-auto=update

#Datasource
spring.datasource.driver-class-name=org.postgresql.Driver
