#Application
spring.application.name=kardex-eletronico
server.port=8080
spring.config.import=optional:file:./config/application-secrets.properties

#Jackson
spring.jackson.property-naming-strategy=SNAKE_CASE

#JPA
spring.jpa.hibernate.ddl-auto=update

#Datasource
spring.datasource.driver-class-name=org.postgresql.Driver
